stages:
  - test

integration-test:
  stage: test
  image: rifqiakrm/godog-base-builder:1.0.2-alpine
  allow_failure: true
  before_script:
    - make tests > /dev/null 2>&1 || FAILED=true
    - if [ $FAILED ]; then bin/fix-failure-report.sh; fi
  script:
    - make generate.report
  artifacts:
    name: "integration-test-report-$CI_PIPELINE_ID"
    paths:
        - report_*.html
  only:
    - /^test-.*$/
  tags:
    - your-runner-tag

integration-test-per-feature:
  stage: test
  image: rifqiakrm/godog-base-builder:1.0.2-alpine
  before_script:
    - make test feature=example > /dev/null 2>&1 || FAILED=true
    - if [ $FAILED ]; then bin/fix-failure-report.sh; fi
  script:
    - make generate.report
  artifacts:
    name: "integration-test-report-$CI_PIPELINE_ID"
    paths:
      - report_*.html
  only:
    - /^test.feature-.*$/
  tags:
    - your-runner-tag